version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/urlshortener
      - REDIS_URL=redis://redis:6379/0
      - FLASK_ENV=production
      - SECRET_KEY=your-production-secret-key-change-this
      - BASE_URL=http://localhost:5000
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
    command: >
      sh -c "sleep 10 && 
             python -c 'from app import create_app, db; app = create_app(); app.app_context().push(); db.create_all()' && 
             gunicorn --bind 0.0.0.0:5000 --workers 4 run:app"

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=urlshortener
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: